# Generated by Django 5.2.6 on 2025-10-09 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='club_image/')),
                ('caption', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club_logos/')),
                ('introduction', models.TextField(blank=True)),
                ('our_goal', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('society', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('attendees', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('sport', 'Sport'), ('cultural', 'Cultural'), ('math', 'Math'), ('drama', 'Drama'), ('cybersecurity', 'Cyber Security'), ('software-hardware', 'Software & Hardware'), ('english-learning', 'English Learning'), ('debating-speaking', 'Debating & Public Speaking'), ('other', 'Other')], default='other', max_length=50)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('club', models.ForeignKey(blank=True, help_text='Event organizing club', null=True, on_delete=django.db.models.deletion.CASCADE, to='ClubNest.club')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubNest.club')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubNest.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ClubNest.participation')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics/')),
                ('department', models.CharField(blank=True, choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('Civil', 'Civil'), ('Pharmacy', 'Pharmacy'), ('ENG', 'ENG'), ('Archi', 'Archi'), ('BBA', 'BBA')], max_length=50, null=True)),
                ('semester', models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], max_length=10, null=True)),
                ('clubs', models.ManyToManyField(blank=True, through='ClubNest.Membership', to='ClubNest.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubNest.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('profile', 'club')},
        ),
    ]
