# Generated by Django 5.2.6 on 2025-09-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upcoming_event_images/')),
            ],
        ),
    ]
