# Generated by Django 5.2.6 on 2025-10-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sponsor Name')),
                ('logo', models.ImageField(upload_to='sponsors/logos/', verbose_name='Logo')),
                ('website_link', models.URLField(blank=True, null=True, verbose_name='Website Link')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority (Lower number appears first)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Sponsor / Partner',
                'verbose_name_plural': 'Sponsors / Partners',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
