# Generated by Django 5.2.6 on 2025-09-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNest', '0002_upcomingevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='description',
            new_name='caption',
        ),
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('Civil', 'Civil'), ('Pharmacy', 'Pharmacy'), ('ENG', 'ENG'), ('Archi', 'Archi'), ('BBA', 'BBA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], max_length=10, null=True),
        ),
    ]
