# Generated by Django 5.2.6 on 2025-10-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNest', '0002_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description (About the Sponsor)'),
        ),
    ]
