# Generated by Django 5.2 on 2025-10-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNest', '0003_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='value',
            new_name='rating',
        ),
    ]
