# Generated by Django 5.2.6 on 2025-09-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNest', '0003_rename_description_club_caption_club_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='about_us',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='club',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
