# Generated by Django 5.2.6 on 2025-10-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNest', '0003_sponsor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='sponsors', to='ClubNest.club'),
        ),
    ]
