# Generated by Django 5.2 on 2025-10-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNest', '0004_rename_value_rating_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
