# Generated by Django 5.2.6 on 2025-09-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNest', '0004_club_about_us_club_contact_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', unique=True),
            preserve_default=False,
        ),
    ]
