# Generated by Django 5.2.6 on 2025-09-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNest', '0006_event_delete_upcomingevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='about_us',
            new_name='introduction',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='mission',
            new_name='our_goal',
        ),
        migrations.RemoveField(
            model_name='club',
            name='vision',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
