# Generated by Django 5.2.6 on 2025-09-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNest', '0007_rename_about_us_club_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='club_image/'),
        ),
    ]
