# Generated by Django 5.2.6 on 2025-09-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNest', '0009_club_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('society', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('attendees', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('sport', 'Sport'), ('cultural', 'Cultural'), ('math', 'Math'), ('drama', 'Drama'), ('cybersecurity', 'Cyber Security'), ('software-hardware', 'Software & Hardware'), ('english-learning', 'English Learning'), ('debating-speaking', 'Debating & Public Speaking')], default='other', max_length=50)),
                ('image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
