# Generated by Django 5.2.6 on 2025-10-01 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNest', '0010_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Event organizing club', null=True, on_delete=django.db.models.deletion.CASCADE, to='ClubNest.club'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('sport', 'Sport'), ('cultural', 'Cultural'), ('math', 'Math'), ('drama', 'Drama'), ('cybersecurity', 'Cyber Security'), ('software-hardware', 'Software & Hardware'), ('english-learning', 'English Learning'), ('debating-speaking', 'Debating & Public Speaking'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubNest.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ClubNest.participation')),
            ],
        ),
    ]
