# Generated by Django 5.2.6 on 2025-10-06 03:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNest', '0011_event_club_alter_event_category_participation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='pdf_file',
            new_name='pdf',
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
